    SELECT
    SNOWFLAKE.ACCOUNT_USAGE.TABLES.TABLE_ID as TABLE_ID,
    TABLE_CATALOG,
    CREATED,
    TABLE_NAME,
    TABLE_SCHEMA,
    TABLE_OWNER,
    TABLE_TYPE,
    IS_TRANSIENT,
    CLUSTERING_KEY,
    ROW_COUNT,
    BYTES,
    RETENTION_TIME,
    LAST_ALTERED,
    AUTO_CLUSTERING_ON,
    COMMENT,
    COLUMN_COUNT
FROM
    SNOWFLAKE.ACCOUNT_USAGE.TABLES 
    LEFT JOIN (
        SELECT
            TABLE_ID,
            COUNT(DISTINCT COLUMN_ID) COLUMN_COUNT
        FROM
            SNOWFLAKE.ACCOUNT_USAGE.COLUMNS
        GROUP BY
            TABLE_ID
    ) C ON C.TABLE_ID = SNOWFLAKE.ACCOUNT_USAGE.TABLES.TABLE_ID
    WHERE DELETED IS NULL;